### PR TITLE
Update Dockerfile comments

### PR DESCRIPTION
**Pull request by 64J0**
## Description:

With this PR, I want to update the `src/Dockerfile` comments. Those changes are only “cosmetic” in the sense that I'm not adding any behavior, just updating the comments to make this file look more beautiful.

Let me know if you'd like to change something.

### CODE REVIEW

**Comment by 64J0** [comment]
Hey, just to know, where is this Dockerfile used?

**Comment by 64J0** [comment]
Any updated on this?

**Comment by kMutagene** [comment]
>Hey, just to know, where is this Dockerfile used?

This is the dockerfile used by binder to host the notebooks (when you click on "open in binder" on the tutorials pages)
e.g.: https://mybinder.org/v2/gh/fslaborg/fslaborg.github.io/gh-pages?filepath=content/tutorials/002_clustering_kMeans.ipynb

These fail currently because we need .net 6 for the latest dotnet interactive tool - another reason why splitting the website (which needs .net 5 due to fornax being .net 5) from the blog.

**Comment by 64J0** [comment]
I see, thanks for the explanation @kMutagene.

**Pull request merged**
