### PR TITLE
Changed Foogle to XPlot

### PR DESCRIPTION
**Pull request by amieres**
Also moved the `open`s closer to usage

### CODE REVIEW

**Comment by tpetricek** [comment]
Could you leave the `open` where they were? The text says that we "reference all the necessary libraries" and lists the libraries - so I think having all the `open` statements right there makes sense.

Otherwise, this looks good - thanks!

**Comment by amieres** [comment]
You are welcome!
Actually, thank you for all your work.

**Comment by dsyme** [comment]
@amieres thanks for the contribution above. I'm working with @zyzhu to help update Deedle, RProvider, FsLab.  If you would like to help in this process please let us know! thanks

**Comment by amieres** [comment]
@dsyme  
Sure, I am happy to help. 
Just, let me know, what can I do?

**Comment by dsyme** [comment]
@amieres I made an initial list here: https://github.com/fslaborg/FsLab/issues/137

**Pull request merged**
