### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by 64J0**
## Description:

Updating this project's README with those changes:

* Mention .net6 instead of .net5 (current LTS version);
* Fix uppercase words;
* Split the word `datascience` into `data science`, which is the correct version;
* Fix typo;
* ~~Update the minimum version necessary to build this project, from `.netcore 3.1.x` to `.netcore 5.x`~~ (this update depends on this PR https://github.com/fslaborg/fslaborg.github.io/pull/43)

Let me know if you'd like to revert something in the text.

### CODE REVIEW

**Comment by 64J0** [comment]
Updated the PR description.

**Comment by 64J0** [comment]
Any update on this?

**Comment by 64J0** [comment]
Any update on this?

**Comment by 64J0** [comment]
I'm assuming this project is dead (or not maintained anymore), so I'm removing my PRs.

**Comment by kMutagene** [comment]
> I'm assuming this project is dead (or not maintained anymore), so I'm removing my PRs.

It is more like i just lost sight of these PRs. However, since the blog moved to a separate repo they are not correctly targeted here. Anyways, sorry for the silence

**Comment by 64J0** [comment]
Hello @kMutagene. Got it, thanks for the update.

**Pull request closed without merging**
